game_bot/urls.py
from django.contrib import admin
from django.urls import path
from .views import ScoreListView


app_name = 'game_bot'

urlpatterns = [
    path('', ScoreListView.as_view(), name='score_list')
]

tg_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

app_name = 'tg_bot'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('games/', include('game_bot.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UserListView

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='users_list'),
]

game_bot/models.py
from django.db import models
from users.models import CustomUser


class Games(models.Model):
    name = models.CharField('Game name', max_length=100, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/games/{self.id}/'


class GameSession(models.Model):
    created_at = models.DateTimeField()
    game = models.ForeignKey(Games, on_delete=models.CASCADE, related_name='session_game', default='default_game')


class GameScores(models.Model):
    game = models.ForeignKey(Games, on_delete=models.CASCADE, blank=False, related_name='scores_game', default='default_game', to_field='name')
    game_session = models.ForeignKey(GameSession, on_delete=models.CASCADE, related_name='game_session')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user', to_field='username')
    score = models.IntegerField()

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):

    class Meta():
        ordering = ["username"]

    def __str__(self):
        return self.get_full_name()

    def get_absolute_ulr(self):
        return "/users/"

game_bot/views.py
from django.shortcuts import render
from .models import GameScores
from django.views.generic.list import ListView


class ScoreListView(ListView):
    model = GameScores
    template_name = 'scores_list.html'
    context_object_name = 'scores_list'

tg_bot/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

users/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import CustomUser
from django.core.paginator import Paginator

class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser
    context_object_name = 'users_list'
    template_name = 'users_list.html'
    paginate_by = 10

    def listing(request):
        user_list = CustomUser.objects.all()
        paginator = Paginator(user_list, 10)
        page_number = request.Get.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'user_index.html', {'page_obj': page_obj})

game_bot/templates/scores_list.html
{% extends 'index.html' %}
{% load bootstrap4 %}

{% if bootstrap_messages %}
	{% block message %}
		{% bootstrap_messages %}
	{% endblock message %}
{% endif %}

{% block content %}
{% if user.is_authenticated %}
    <h2>Users</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>User ID</th>
              <th>Nickname</th>
              <th>Name</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users_list %}
            <tr>
              <td>{{user.id}}</td>
              <td>{{user.username}}</td>
              <td>{{user}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;first</a>
            <a href="?page={{ p.previous_page_previous_page_number }}">{{ previous }}</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ next }}</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ last }}&raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock content %}

tg_bot/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href={% url 'index' %}>
                  <span data-feather="home"></span>
                  Home <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href={% url 'users:users_list' %}>
                  <span data-feather="home"></span>
                  Users <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Integrations
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

        {% block dashboard %}
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

          <canvas class="my-4" id="myChart" width="900" height="380"></canvas>
          {% endblock dashboard %}

          {% block content %}
          {% endblock content %}

          </div>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

users/templates/users_list.html
{% extends 'index.html' %}
{% load bootstrap4 %}

{% if bootstrap_messages %}
	{% block message %}
		{% bootstrap_messages %}
	{% endblock message %}
{% endif %}

{% block content %}
{% if user.is_authenticated %}
    <h2>Users</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>User ID</th>
              <th>Nickname</th>
              <th>Name</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users_list %}
            <tr>
              <td>{{user.id}}</td>
              <td>{{user.username}}</td>
              <td>{{user}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;first</a>
            <a href="?page={{ p.previous_page_previous_page_number }}">{{ previous }}</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ next }}</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ last }}&raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock content %}